const ROLES = require("./roles");
const PERMISSIONS = require("./permissions");


const ROLE_PERMISSIONS = {

    [ROLES.OWNER]: [
        PERMISSIONS.TENANT_UPDATE,
        PERMISSIONS.TENANT_DELETE,
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_UPDATE,
        PERMISSIONS.PROFILE_VIEW,
        PERMISSIONS.PROFILE_UPDATE
    ],


    [ROLES.ADMIN]: [
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_UPDATE,
        PERMISSIONS.PROFILE_VIEW,
        PERMISSIONS.PROFILE_UPDATE
    ],


    [ROLES.MANAGER]: [
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.PROFILE_VIEW,
        PERMISSIONS.PROFILE_UPDATE
    ],


    [ROLES.EMPLOYEE]: [
        PERMISSIONS.PROFILE_VIEW,
        PERMISSIONS.PROFILE_UPDATE
    ]

};


module.exports = ROLE_PERMISSIONS;