const ROLES = require("./roles");

const PERMISSIONS = require("./permissions");

const ROLE_PERMISSIONS = {

    [ROLES.OWNER]: [
        PERMISSIONS.TENANT_UPDATE,
        PERMISSIONS.TENANT_DELETE,

        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_UPDATE,

        PERMISSIONS.CUSTOMER_CREATE,
        PERMISSIONS.CUSTOMER_VIEW,
        PERMISSIONS.CUSTOMER_UPDATE,
        PERMISSIONS.CUSTOMER_DELETE,

        PERMISSIONS.PROFILE_VIEW,
        PERMISSIONS.PROFILE_UPDATE
    ],


    [ROLES.ADMIN]: [
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_UPDATE,

        PERMISSIONS.CUSTOMER_CREATE,
        PERMISSIONS.CUSTOMER_VIEW,
        PERMISSIONS.CUSTOMER_UPDATE,
        PERMISSIONS.CUSTOMER_DELETE,

        PERMISSIONS.PROFILE_VIEW,
        PERMISSIONS.PROFILE_UPDATE
    ],


    [ROLES.MANAGER]: [
        PERMISSIONS.CUSTOMER_CREATE,
        PERMISSIONS.CUSTOMER_VIEW,
        PERMISSIONS.CUSTOMER_UPDATE,
        PERMISSIONS.CUSTOMER_DELETE,

        PERMISSIONS.PROFILE_VIEW,
        PERMISSIONS.PROFILE_UPDATE
    ],


    [ROLES.EMPLOYEE]: [
        PERMISSIONS.CUSTOMER_VIEW,

        PERMISSIONS.PROFILE_VIEW,
        PERMISSIONS.PROFILE_UPDATE
    ]

};

module.exports = ROLE_PERMISSIONS;